name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
        vs-prerelease: true
    
    - name: Premake
      run: Vendor/Premake/premake5.exe vs2022

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: msbuild Snowflake.sln

    - name: Test
      run: dotnet test Test/Snowflake.Test --no-restore --no-build --verbosity normal
